language: csharp
solution: WordCounterBot.sln
mono: none
dotnet: 3.0
jobs:
  include:
    - stage: build
      script:
      - dotnet restore
      - dotnet build
    - stage: deploy
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push "$DOCKER_USERNAME/multi-purpose-tg-bot"
      on:
        branch: master
services:
  - docker