version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: multi-purpose-tg-bot:latest
    ports:
      - "443"
    network_mode: "host"
    env_file: env
    restart: unless-stopped
    secrets:
      - source: bot-config
        target: /app/appsettings.json
      - source: bot-ssl-crt
        target: /app/bot-ssl.crt
secrets:
  bot-ssl-crt:
    file: ./ssl.crt
  bot-config:
    file: ./APIL/appsettings.json